import type { Metadata } from "next";
import '@mantine/core/styles.css';
import React from 'react';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { theme } from '../../theme';
import {Rubik} from 'next/font/google';
import '@mantine/carousel/styles.css';
import './global.css'
import Shell from "../components/navbar/navbar";



const rubik = Rubik({
  weight: ['300','400', '500', '700'],
  display: 'swap',
  variable: '--Rubik',
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable}`}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/vercel.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme}  defaultColorScheme="dark">
          <Shell>{children}</Shell>
        </MantineProvider>
      </body>
    </html>
  );
}
